spring.application.name=JyPS

#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Mostrar el SQL en consola (muy útil para debuggear)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
