spring.application.name=JyPS


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.datasource.hikari.max-lifetime=120000

spring.datasource.hikari.idle-timeout=60000

spring.datasource.hikari.keepalive-time=30000